### PR TITLE
Migrate commands to drush 9

### PR DESCRIPTION
**Pull request by phcorp**
| Q             | A
| ------------- | ---
| Branch?       | 2913775-drush9 (see #22) 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by fgm** [comment]
Looks rather good. But there's so little code in that worker service: can't it take off more from the consumer, or be subsumed in it ?

**Comment by phcorp** [comment]
Done

**Comment by fgm** [comment]
Looks good. I'll merge it once I'm donné testing. Does it interact with the logger issue ?

**Comment by phcorp** [comment]
Probably not, I'm not aware of this issue

**Comment by phcorp** [comment]
I merged @pguillard PR, does it solve the previously mentioned logger issue?

**Comment by fgm** [comment]
Merged outside Github, thanks.

**Pull request closed without merging**
