### PR TITLE
Add an example module

### PR DESCRIPTION
**Pull request by Saphyel**
Provides an example module

### CODE REVIEW

**Comment by Saphyel** [comment]
@FGM I think rather than using the old fashion way (settings.php) for configure the queues and etc.. is possible that we switch to use the services file?

**Comment by fgm** [comment]
Could be done, but IMO it's not necessarily a good idea : services are
rather a part of application configuration while settings are
per-environment, and the exact choice of queue driver and connection
strings is very much a per-environment setting (dev vs prod...). OTOH,
services.yml tends to be also used as per-environment, from various D8
projects I've seen in the last 12 months, so it's really a matter of
preference. Not forgetting that changing something in services.yml means a
flush before it's active.

2016-03-21 17:44 GMT+01:00 Carlos Jimenez notifications@github.com:

**Comment by Saphyel** [comment]
@FGM  In that case I think you can use something like: `development.services.yml` or `default.services.yml`, etc...
I never liked see a lot of custom code in `settings.php`, the less code there the better...

**Comment by fgm** [comment]
Let's see how it could look before deciding : could you provide a sample services.yml declaration (just the declaration, no need for the code for now) to see how it could look best ?

**Pull request closed without merging**
