### PR TITLE
Feature/exchange queues config

### PR DESCRIPTION
**Pull request by pvhee**
A different proposal to support configurable exchanges and queues.
### Proposed changes
- Queues and (optional) exchanges can be defined in `.yml` files that can be part of the active config of any module or profile, much like how [message_broker](https://www.drupal.org/project/message_broker) defined exchanges/queues in a `.json` file
- If no config is provided, default options will be used.
### Example config

``` yml
exchanges:
  default:
    type: 'direct'
    passive: false
    durable: true
    auto_delete: false
    internal: false
    nowait: false

queues:
  queue1:
    passive: false
    durable: true
    exclusive: false
    auto_delete: true
    nowait: false
    routing_keys:
      - 'default.route1'
  queue2:
    passive: false
    durable: true
    exclusive: false
    auto_delete: true
    nowait: false
    routing_keys:
      - 'default.route2'
```

Note that this also removes the need for declaring any hooks, so I removed `hook_rabbitmq_queue_info`.
### Future improvements

The next part could be to make a UI for this, and to automatically register these queues to use the `queue.rabbitmq` interface (and thus making `settings.php` only contain connectivity settings which might differ per environment, but have the queue info shared for the whole site).

### CODE REVIEW

**Comment by pvhee** [comment]
@FGM any feedback on this? FYI @bimsonz @saphyel

**Comment by Saphyel** [comment]
I don't think we need the array bindings and routing_key is already saying the exchange so is a bit duplicate things...

**Comment by pvhee** [comment]
Not sure I understand what you mean @Saphyel?

**Comment by Saphyel** [comment]
@pvhee You can use:

```
  queue2:
    passive: false
    durable: true
    exclusive: false
    auto_delete: true
    nowait: false
    **routing_key: 'default.route2'**
```

it'll be also clear: you are binding the exchange _default_ with the queue _route2_, there's no need to add extra elements

**Comment by pvhee** [comment]
@Saphyel but then we'd need to parse the routing_key and split it on the `.` to find the associated exchange?

**Comment by Saphyel** [comment]
mhh what about just say the exchange? because is always the format `exchange.queue` and we always know the queue. An example: 

```
route2:
  blabla: blabla
  routing_key:
    -'default'
    -'otherteam'
```

exchange `otherteam` is route to the queue `route2` using `otherteam.route2`

**Comment by pvhee** [comment]
@Saphyel the routing_key can be anything, it is not necessarily the same as the queue, and allows consumers to only consume messages on the queue with a certain routing key

**Comment by pvhee** [comment]
@Saphyel I've changed the format for defining routing keys with exchanges, see the example above,

**Pull request merged**
